apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ocp-openvpn-git
  namespace: {{ .Values.namespace }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ocp-openvpn-git:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: dev
      uri: https://github.com/greeninja/ocp-openvpn.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Containerfile
      from:
        kind: DockerImage
        name: registry.redhat.io/ubi8/ubi
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange