apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "nctap",
            "namespace": "{{ .Values.namespace }}",
            "mac": "00:11:22:33:44:55"
          }]
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.registry }}/{{ .Values.namespace}}/{{ .Values.image }}:latest
        imagePullPolicy: Always
        name: openvpn-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: 
          privileged: false
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN", "MKNOD"]
        volumeMounts:
        - mountPath: /etc/openvpn/server
          name: openvpn-server
        # - mountPath: /dev/net/tun
        #   name: net-tun
        #   readOnly: false
      initContainers:
      - name: openvpn-init
        imagePullPolicy: Always
        image: {{ .Values.registry }}/{{ .Values.namespace}}/{{ .Values.init_image }}:latest
        volumeMounts:
        - mountPath: /etc/openvpn/server
          name: openvpn-server
      volumes:
      - name: openvpn-server
        emptyDir: {}
      - name: net-tun
        hostPath:
          path: /dev/net/tun
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: openvpn