apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        # k8s.v1.cni.cncf.io/networks: '[
        #   {
        #   "name": "tap",
        #   "namespace": "{{ .Values.namespace }}",
        #   "interface": "ext0",
        #   "mac": "50:00:00:00:00:10"
        #   }    
        # ]'
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: openvpn-as
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: 
          privileged: false
          capabilities:
            add: ["NET_ADMIN"]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: openvpn