apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-crio-config
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/crio/crio.conf.d/99-ciro-allowed-devices
          overwrite: true
          contents:
            source: data:text/plain;charset=utf-8;base64,W2NyaW8ucnVudGltZV0KYWxsb3dlZF9kZXZpY2VzID0gWyIvZGV2L2Z1c2UiLCIvZGV2L25ldC90dW4iXQo=