apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-crio-config
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - path: /etc/crio/crio.conf.d/99-ciro-allowed-devices
        mode: 0644 
        overwrite: true
        contents:
          inline: |
            [crio]
              [crio.runtime]
                allowed_devices = ["/dev/fuse","/dev/net/tun"]