apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-setsebool
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
      - enabled: true
        name: setsebool.service
        contents: |
          [Unit]
          Description=Set SELinux boolean for the TAP CNI plugin
          Before=kubelet.service

          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/setsebool container_use_devices=on
          RemainAfterExit=true

          [Install]
          WantedBy=multi-user.target graphical.target
        storage:
    files:
      - path: /etc/crio/crio.conf.d/99-ciro-allowed-devices
        mode: 0644 
        overwrite: true
        contents:
          inline: |
            [crio]
              [crio.runtime]
                allowed_devices = ["/dev/fuse","/dev/net/tun"]