apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: tap
  namespace: {{ .Values.namespace }}
spec:
  config: '{
     "cniVersion": "0.4.0",
     "name": "tap",
     "plugins": [
       {
         "type": "tap",
         "owner": 0,
         "group": 0,
         "multiQueue": true,
         "selinuxcontext": "system_u:system_r:container_t:s0"
       }
     ]
  }'