apiVersion: v1
kind: ServiceAccount
metadata:
  name: openvpn
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "5"
secrets: []