apiVersion: v1
kind: Service
metadata:
  name: openvpn-as
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 1194
      protocol: UDP
      targetPort: 1194
      nodePort: 31194