FROM registry.redhat.io/ubi8/ubi

RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN dnf install -y openvpn easy-rsa
# Setup PKI & certs
RUN mkdir /easy-rsa
RUN chgrp -R 0 /easy-rsa
RUN chmod -R g=u /easy-rsa
RUN chown -R 1001:0 /easy-rsa
USER 1001
WORKDIR /easy-rsa
RUN cp -rd /usr/share/easy-rsa/3/* /easy-rsa/
COPY files/vars /easy-rsa/vars
RUN ./easyrsa init-pki
RUN echo 'testing' | ./easyrsa build-ca
RUN ./easyrsa gen-req server batch
# RUN cp pki/private/server.key pki/ca.crt /etc/openvpn/server/
RUN yes yes | ./easyrsa sign-req server server
# RUN cp pki/issued/server.crt /etc/openvpn/server/
# Setup extra security
RUN openvpn --genkey --secret ta.key
# RUN cp ta.key /etc/openvpn/server/
# Generate client keys
RUN mkdir client-configs
RUN echo 'client1' | ./easyrsa gen-req client1
RUN yes yes | ./easyrsa sign-req client client1
# RUN cp pki/private/client1.key pki/issued/client1.crt ta.key client-configs/
# Copy openvpn config file
COPY files/server.conf server.conf
# RUN cp server.cnf /etc/openvpn/server/server.conf
COPY --chown=1001:0 files/setup.sh setup.sh
RUN chmod 775 setup.sh

ENTRYPOINT [ "/bin/bash", "-c", "/easy-rsa/setup.sh" ]